head.load("js/lib/jquery.js",
					"js/lib/cycle.js",
					"js/lib/jquery-ui.min.js",
					"js/lib/cycle.carousel.js",
					"js/lib/jquery.mCustomScrollbar.min.js",
					"js/lib/slick.min.js",
					"js/lib/jquery.tooltipster.min.js",
					"js/lib/cropper.min.js",
					"js/common.js");
